int a = 1

task main()
{
	while(a=>2)
	{
		playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 16 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteFSharp , octave3 , -16 )
playNote ( noteD , octave3 , -16 )
playNote ( noteB , octave2 , -16 )
playNote ( noteA , octave3 , -16 )
playNote ( noteFSharp , octave3 , -16 )
playNote ( noteB , octave2 , -16 )
playNote ( noteD , octave3 , -16 )
playNote ( noteFSharp , octave3 , -16 )
playNote ( noteA , octave3 , -16 )
playNote ( noteFSharp , octave3 , -16 )
playNote ( noteD , octave3 , -16 )
playNote ( noteB , octave2 , -16 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 16 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteE , octave2 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteE , octave2 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteE , octave2 , -16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteG , octave2 , -16 )
playNote ( noteB , octave2 , -16 )

playNote ( noteA , octave2 , 16 )
playNote ( noteA , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteG , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteF , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteDSharp , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteF , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteA , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteG , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteF , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteDSharp , octave2 , -2 )

playNote ( noteA , octave2 , 16 )
playNote ( noteA , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteG , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteF , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteDSharp , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteF , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteA , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteG , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteA , octave3 , -16 )
playNote ( noteF , octave3 , -16 )
playNote ( noteD , octave3 , -16 )
playNote ( noteA , octave3 , -16 )
playNote ( noteF , octave3 , -16 )
playNote ( noteD , octave3 , -16 )
playNote ( noteC , octave2 , -16 )
playNote ( noteA , octave3 , -16 )
playNote ( noteF , octave3 , -16 )
playNote ( noteA , octave3 , -16 )
playNote ( noteF , octave3 , -16 )
playNote ( noteD , octave3 , -16 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteCSharp , octave3 , 16 )
playNote ( noteCSharp , octave2 , 8 )
playNote ( noteCSharp , octave3 , 16 )
playNote ( noteB , octave3 , 8 )
playNote ( noteCSharp , octave3 , 16 )
playNote ( noteA , octave3 , 8 )
playNote ( noteCSharp , octave3 , 16 )
playNote ( noteG , octave3 , 8 )
playNote ( noteCSharp , octave3 , 16 )
playNote ( noteGSharp , octave3 , 8 )
playNote ( noteA , octave3 , 8 )
playNote ( noteB , octave2 , 16 )
playNote ( noteB , octave3 , 8 )
playNote ( noteB , octave2 , 16 )
playNote ( noteA , octave3 , 8 )
playNote ( noteB , octave2 , 16 )
playNote ( noteG , octave3 , 8 )
playNote ( noteB , octave2 , 16 )
playNote ( noteF , octave3 , -2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 16 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteE , octave2 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteE , octave2 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteE , octave2 , -16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteG , octave2 , -16 )
playNote ( noteB , octave2 , -16 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 16 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteFSharp , octave3 , -16 )
playNote ( noteDSharp , octave3 , -16 )
playNote ( noteB , octave2 , -16 )
playNote ( noteFSharp , octave3 , -16 )
playNote ( noteDSharp , octave3 , -16 )
playNote ( noteB , octave2 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteD , octave3 , -16 )
playNote ( noteB , octave2 , -16 )
playNote ( noteDSharp , octave2 , -16 )
playNote ( noteDSharp , octave3 , -16 )
playNote ( noteB , octave2 , -16 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 16 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave2 , -16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteG , octave2 , -16 )
playNote ( noteE , octave2 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteD , octave2 , -16 )
playNote ( noteE , octave2 , -16 )
playNote ( noteG , octave2 , -16 )
playNote ( noteE , octave2 , -16 )
playNote ( noteG , octave3 , -16 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteA , octave2 , 16 )
playNote ( noteA , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteG , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteF , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteDSharp , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteF , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteA , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteG , octave3 , 8 )
playNote ( noteA , octave2 , 16 )
playNote ( noteA , octave3 , -16 )
playNote ( noteF , octave3 , -16 )
playNote ( noteD , octave3 , -16 )
playNote ( noteA , octave3 , -16 )
playNote ( noteF , octave3 , -16 )
playNote ( noteD , octave3 , -16 )
playNote ( noteC , octave2 , -16 )
playNote ( noteA , octave3 , -16 )
playNote ( noteF , octave3 , -16 )
playNote ( noteA , octave3 , -16 )
playNote ( noteF , octave3 , -16 )
playNote ( noteD , octave3 , -16 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , -2 )

playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteASharp , octave2 , 16 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave2 , 8 )
playNote ( noteC , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteE , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteD , octave3 , 8 )
playNote ( noteE , octave2 , 16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteE , octave3 , -16 )
playNote ( noteB , octave2 , -16 )
playNote ( noteE , octave3 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteC , octave2 , -16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteB , octave3 , -16 )
playNote ( noteG , octave3 , -16 )
playNote ( noteE , octave3 , -16 )
a++
	}

	while(a > 2)
	{
		playNote ( noteB , octave1 , 31)
playNote ( noteC , octave1 , 33)
playNote ( noteCSharp , octave1 ,  35)
playNote ( noteD , octave1 , 37)
playNote ( noteDSharp , octave1 ,  39)
playNote ( noteE , octave1 , 41)
playNote ( noteF , octave1 , 44)
playNote ( noteFSharp , octave1 ,  46)
playNote ( noteG , octave1 , 49)
playNote ( noteGSharp , octave1 ,  52)
playNote ( noteA , octave1 , 55)
playNote ( noteASharp , octave1 ,  58)
playNote ( noteB , octave1 , 62)
playNote ( noteC , octave2 , 65)
playNote ( noteCSharp , octave2 ,  69)
playNote ( noteD , octave2 , 73)
playNote ( noteDSharp , octave2 ,  78)
playNote ( noteE , octave2 , 82)
playNote ( noteF , octave2 , 87)
playNote ( noteFSharp , octave2 ,  93)
playNote ( noteG , octave2 , 98)
playNote ( noteGSharp , octave2 ,  104)
playNote ( noteA , octave2 , 110)
playNote ( noteASharp , octave2 ,  117)
playNote ( noteB , octave2 , 123)
playNote ( noteC , octave3 , 131)
playNote ( noteCSharp , octave3 ,  139)
playNote ( noteD , octave3 , 147)
playNote ( noteDSharp , octave3 ,  156)
playNote ( noteE , octave3 , 165)
playNote ( noteF , octave3 , 175)
playNote ( noteFSharp , octave3 ,  185)
playNote ( noteG , octave3 , 196)
playNote ( noteGSharp , octave3 ,  208)
playNote ( noteA , octave3 , 220)
playNote ( noteASharp , octave3 ,  233)
playNote ( noteB , octave3 , 247)
playNote ( noteC , octave2 , 262)
playNote ( noteCSharp , octave2 ,  277)
playNote ( noteD , octave2 , 294)
playNote ( noteDSharp , octave2 ,  311)
playNote ( noteE , octave2 , 330)
playNote ( noteF , octave2 , 349)
playNote ( noteFSharp , octave2 ,  370)
playNote ( noteG , octave2 , 392)
playNote ( noteGSharp , octave2 ,  415)
playNote ( noteA , octave2 , 440)
playNote ( noteASharp , octave2 ,  466)
playNote ( noteB , octave2 , 494)
playNote ( noteC , octave3 , 523)
playNote ( noteCSharp , octave3 ,  554)
playNote ( noteD , octave3 , 587)
playNote ( noteDSharp , octave3 ,  622)
playNote ( noteE , octave3 , 659)
playNote ( noteF , octave3 , 698)
playNote ( noteFSharp , octave3 ,  740)
playNote ( noteG , octave3 , 784)
playNote ( noteGSharp , octave3 ,  831)
playNote ( noteA , octave3 , 880)
playNote ( noteASharp , octave3 ,  932)
playNote ( noteB , octave3 , 988)
playNote ( noteC , octave2 , 1047)
playNote ( noteCSharp , octave2 ,  1109)
playNote ( noteD , octave2 , 1175)
playNote ( noteDSharp , octave2 ,  1245)
playNote ( noteE , octave2 , 1319)
playNote ( noteF , octave2 , 1397)
playNote ( noteFSharp , octave2 ,  1480)
playNote ( noteG , octave2 , 1568)
playNote ( noteGSharp , octave2 ,  1661)
playNote ( noteA , octave2 , 1760)
playNote ( noteASharp , octave2 ,  1865)
playNote ( noteB , octave2 , 1976)
playNote ( noteC , octave3 , 2093)
playNote ( noteCSharp , octave3 ,  2217)
playNote ( noteD , octave3 , 2349)
playNote ( noteDSharp , octave3 ,  2489)
playNote ( noteE , octave3 , 2637)
playNote ( noteF , octave3 , 2794)
playNote ( noteFSharp , octave3 ,  2960)
playNote ( noteG , octave3 , 3136)
playNote ( noteGSharp , octave3 ,  3322)
playNote ( noteA , octave3 , 3520)
playNote ( noteASharp , octave3 ,  3729)
playNote ( noteB , octave3 , 3951)
playNote ( noteC , octave2 , 4186)
playNote ( noteCSharp , octave2 ,  4435)
playNote ( noteD , octave2 , 4699)
playNote ( noteDSharp , octave2 ,  4978)
	}
}
